//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mzmr.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mzmr.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] abilityBombGFX {
            get {
                object obj = ResourceManager.GetObject("abilityBombGFX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] abilityChargeGFX {
            get {
                object obj = ResourceManager.GetObject("abilityChargeGFX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] abilityEnergyGFX {
            get {
                object obj = ResourceManager.GetObject("abilityEnergyGFX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] abilityGravityGFX {
            get {
                object obj = ResourceManager.GetObject("abilityGravityGFX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] abilityGripGFX {
            get {
                object obj = ResourceManager.GetObject("abilityGripGFX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] abilityHiGFX {
            get {
                object obj = ResourceManager.GetObject("abilityHiGFX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] abilityIceGFX {
            get {
                object obj = ResourceManager.GetObject("abilityIceGFX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] abilityLongGFX {
            get {
                object obj = ResourceManager.GetObject("abilityLongGFX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] abilityMissileGFX {
            get {
                object obj = ResourceManager.GetObject("abilityMissileGFX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] abilityMorphGFX {
            get {
                object obj = ResourceManager.GetObject("abilityMorphGFX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] abilityPlasmaGFX {
            get {
                object obj = ResourceManager.GetObject("abilityPlasmaGFX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] abilityPowerGFX {
            get {
                object obj = ResourceManager.GetObject("abilityPowerGFX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] abilityScrewGFX {
            get {
                object obj = ResourceManager.GetObject("abilityScrewGFX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] abilitySpaceGFX {
            get {
                object obj = ResourceManager.GetObject("abilitySpaceGFX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] abilitySpeedGFX {
            get {
                object obj = ResourceManager.GetObject("abilitySpeedGFX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] abilitySuperGFX {
            get {
                object obj = ResourceManager.GetObject("abilitySuperGFX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] abilityVariaGFX {
            get {
                object obj = ResourceManager.GetObject("abilityVariaGFX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] abilityWaveGFX {
            get {
                object obj = ResourceManager.GetObject("abilityWaveGFX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bombMap {
            get {
                object obj = ResourceManager.GetObject("bombMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap brinstarMap {
            get {
                object obj = ResourceManager.GetObject("brinstarMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chargeMap {
            get {
                object obj = ResourceManager.GetObject("chargeMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chozodiaMap {
            get {
                object obj = ResourceManager.GetObject("chozodiaMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] chozoStatueGFX {
            get {
                object obj = ResourceManager.GetObject("chozoStatueGFX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap crateriaMap {
            get {
                object obj = ResourceManager.GetObject("crateriaMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap energyMap {
            get {
                object obj = ResourceManager.GetObject("energyMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gravityMap {
            get {
                object obj = ResourceManager.GetObject("gravityMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gripMap {
            get {
                object obj = ResourceManager.GetObject("gripMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hiMap {
            get {
                object obj = ResourceManager.GetObject("hiMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iceMap {
            get {
                object obj = ResourceManager.GetObject("iceMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kraidMap {
            get {
                object obj = ResourceManager.GetObject("kraidMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Location]
        ///Number=0
        ///Area=0
        ///Room=0
        ///Minimap=(0,F)
        ///Item=Morph
        ///Varia=(2E0,6FF)
        ///
        ///[Location]
        ///Number=1
        ///Area=0
        ///Room=1
        ///Minimap=(5,E)
        ///Item=Missile
        ///Clip=60CDA4
        ///BG1=60CF4A
        ///Varia=(360,1FF)
        ///Requirements=Morph,Bomb
        ///
        ///[Location]
        ///Number=2
        ///Area=0
        ///Room=5
        ///Minimap=(6,6)
        ///Item=Long
        ///Varia=(278,1FF)
        ///Requirements=Morph
        ///
        ///[Location]
        ///Number=3
        ///Area=0
        ///Room=2
        ///Minimap=(7,F)
        ///Item=Energy
        ///Clip=60D48C
        ///Varia=(720,2BF)
        ///
        ///[Location]
        ///Number=4
        ///Area=0
        ///Room=29
        ///Minimap=(9,B)
        ///Item=Missile
        ///Clip=617076
        ///BG1=617295 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string locations {
            get {
                return ResourceManager.GetString("locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap longMap {
            get {
                object obj = ResourceManager.GetObject("longMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap missileMap {
            get {
                object obj = ResourceManager.GetObject("missileMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap morphMap {
            get {
                object obj = ResourceManager.GetObject("morphMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap norfairMap {
            get {
                object obj = ResourceManager.GetObject("norfairMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] palBomb {
            get {
                object obj = ResourceManager.GetObject("palBomb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] palCharge {
            get {
                object obj = ResourceManager.GetObject("palCharge", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] palGravity {
            get {
                object obj = ResourceManager.GetObject("palGravity", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] palGrip {
            get {
                object obj = ResourceManager.GetObject("palGrip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] palHi {
            get {
                object obj = ResourceManager.GetObject("palHi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] palIce {
            get {
                object obj = ResourceManager.GetObject("palIce", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] palLong {
            get {
                object obj = ResourceManager.GetObject("palLong", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] palMorph {
            get {
                object obj = ResourceManager.GetObject("palMorph", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] palPlasma {
            get {
                object obj = ResourceManager.GetObject("palPlasma", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] palScrew {
            get {
                object obj = ResourceManager.GetObject("palScrew", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] palSpace {
            get {
                object obj = ResourceManager.GetObject("palSpace", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] palSpeed {
            get {
                object obj = ResourceManager.GetObject("palSpeed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] palTank {
            get {
                object obj = ResourceManager.GetObject("palTank", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] palVaria {
            get {
                object obj = ResourceManager.GetObject("palVaria", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] palWave {
            get {
                object obj = ResourceManager.GetObject("palWave", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plasmaMap {
            get {
                object obj = ResourceManager.GetObject("plasmaMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap powerMap {
            get {
                object obj = ResourceManager.GetObject("powerMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ridleyMap {
            get {
                object obj = ResourceManager.GetObject("ridleyMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap screwMap {
            get {
                object obj = ResourceManager.GetObject("screwMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spaceMap {
            get {
                object obj = ResourceManager.GetObject("spaceMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap speedMap {
            get {
                object obj = ResourceManager.GetObject("speedMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap superMap {
            get {
                object obj = ResourceManager.GetObject("superMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tourianMap {
            get {
                object obj = ResourceManager.GetObject("tourianMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap variaMap {
            get {
                object obj = ResourceManager.GetObject("variaMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap waveMap {
            get {
                object obj = ResourceManager.GetObject("waveMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ZM_U_blackPiratePlasma {
            get {
                object obj = ResourceManager.GetObject("ZM_U_blackPiratePlasma", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ZM_U_fixChargeOAM {
            get {
                object obj = ResourceManager.GetObject("ZM_U_fixChargeOAM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ZM_U_hardModeAvailable {
            get {
                object obj = ResourceManager.GetObject("ZM_U_hardModeAvailable", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ZM_U_itemToggle {
            get {
                object obj = ResourceManager.GetObject("ZM_U_itemToggle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ZM_U_metroidIce {
            get {
                object obj = ResourceManager.GetObject("ZM_U_metroidIce", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ZM_U_pauseScreenInfo {
            get {
                object obj = ResourceManager.GetObject("ZM_U_pauseScreenInfo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ZM_U_randomItemBase {
            get {
                object obj = ResourceManager.GetObject("ZM_U_randomItemBase", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ZM_U_removeChozoHints {
            get {
                object obj = ResourceManager.GetObject("ZM_U_removeChozoHints", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ZM_U_removeElevatorCutscenes {
            get {
                object obj = ResourceManager.GetObject("ZM_U_removeElevatorCutscenes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ZM_U_removeNorfairVine {
            get {
                object obj = ResourceManager.GetObject("ZM_U_removeNorfairVine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ZM_U_removeVariaAnim {
            get {
                object obj = ResourceManager.GetObject("ZM_U_removeVariaAnim", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long=13AC0
        ///Charge=13650
        ///Ice=13AD8
        ///Wave=13AF0
        ///Plasma=13BC8
        ///Bomb=13B08
        ///Varia=13B78
        ///Gravity=13BB0
        ///Morph=1316C
        ///Speed=13B20
        ///Hi=13B38
        ///Screw=13B58
        ///Space=13B98
        ///Grip=133AA.
        /// </summary>
        internal static string ZM_U_replaceAbilities {
            get {
                return ResourceManager.GetString("ZM_U_replaceAbilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ZM_U_skipSuitless {
            get {
                object obj = ResourceManager.GetObject("ZM_U_skipSuitless", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ZM_U_unkItems {
            get {
                object obj = ResourceManager.GetObject("ZM_U_unkItems", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
